// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Geometry from "./Geometry.res.js";

function toRad(deg) {
  return deg * Math.PI / 180.0;
}

function toCartesian(param) {
  var rho = param.rho;
  var theta = toRad(param.theta);
  var phi = toRad(param.phi);
  var x = rho * Math.cos(phi) * Math.sin(theta);
  var y = rho * Math.sin(phi);
  var z = rho * Math.cos(phi) * Math.cos(theta);
  return {
          dx: x,
          dy: y,
          dz: z
        };
}

function neighbors(param) {
  var radius = param.radius;
  var center = param.center;
  var color = param.color;
  var rho = 2.0 * radius;
  return [
                  {
                    theta: 0.0,
                    phi: 0.0,
                    rho: rho
                  },
                  {
                    theta: 60.0,
                    phi: 0.0,
                    rho: rho
                  },
                  {
                    theta: 120.0,
                    phi: 0.0,
                    rho: rho
                  },
                  {
                    theta: 180.0,
                    phi: 0.0,
                    rho: rho
                  },
                  {
                    theta: 240.0,
                    phi: 0.0,
                    rho: rho
                  },
                  {
                    theta: 300.0,
                    phi: 0.0,
                    rho: rho
                  },
                  {
                    theta: 90.0,
                    phi: 60.0,
                    rho: rho
                  },
                  {
                    theta: 210.0,
                    phi: 60.0,
                    rho: rho
                  },
                  {
                    theta: 330.0,
                    phi: 60.0,
                    rho: rho
                  }
                ].map(toCartesian).map(function (x) {
                  console.log(x);
                  return x;
                }).map(function (extra) {
                return Geometry.plus(center, extra);
              }).map(function (point) {
              return {
                      color: color,
                      center: point,
                      radius: radius
                    };
            });
}

export {
  toRad ,
  toCartesian ,
  neighbors ,
}
/* No side effect */
