// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Geometry from "./Geometry.res.js";

function toCartesian(param) {
  var radius = param.radius;
  var phi = param.phi;
  var theta = param.theta;
  return {
          dx: radius * Math.sin(theta) * Math.cos(phi),
          dy: radius * Math.sin(theta) * Math.sin(phi),
          dz: radius * Math.cos(theta)
        };
}

function neighbors(param) {
  var radius = param.radius;
  var center = param.center;
  return [
              {
                theta: 0.0,
                phi: 0.0,
                radius: radius
              },
              {
                theta: 60.0,
                phi: 0.0,
                radius: radius
              },
              {
                theta: 120.0,
                phi: 0.0,
                radius: radius
              },
              {
                theta: 180.0,
                phi: 0.0,
                radius: radius
              },
              {
                theta: 240.0,
                phi: 0.0,
                radius: radius
              },
              {
                theta: 300.0,
                phi: 0.0,
                radius: radius
              },
              {
                theta: 90.0 + 0.0,
                phi: 60.0,
                radius: radius
              },
              {
                theta: 90.0 + 120.0,
                phi: 60.0,
                radius: radius
              },
              {
                theta: 90.0 + 240.0,
                phi: 60.0,
                radius: radius
              },
              {
                theta: 90.0,
                phi: -60.0,
                radius: radius
              },
              {
                theta: 90.0 + 120.0,
                phi: -60.0,
                radius: radius
              },
              {
                theta: 90.0 + 240.0,
                phi: -60.0,
                radius: radius
              }
            ].map(toCartesian).map(function (extra) {
              return Geometry.plus(center, extra);
            });
}

export {
  toCartesian ,
  neighbors ,
}
/* No side effect */
