// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Geometry from "./Geometry.res.js";

function pixelToOrigin(param) {
  var up = param.up;
  var match = param.wNormal;
  var left = Geometry.normalize(Geometry.cross(up, match.vector));
  var nUp = Geometry.normalize(up);
  return Geometry.plus(Geometry.plus(match.point, Geometry.scale(0.5 * param.width, left)), Geometry.scale(0.5 * param.height, nUp));
}

export {
  pixelToOrigin ,
}
/* No side effect */
