// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function smallest(arr, size) {
  return Core__Option.map(arr[0], (function (head) {
                return Core__Array.reduce(arr, head, (function (small, value) {
                              if (size(small) < size(value)) {
                                return small;
                              } else {
                                return value;
                              }
                            }));
              }));
}

function inspect(x) {
  console.log(x);
  return x;
}

function dedupe(arr, eq) {
  return Core__Array.reduce(arr, [], (function (acc, s1) {
                var s2 = acc[0];
                if (s2 !== undefined) {
                  if (eq(Caml_option.valFromOption(s2), s1)) {
                    return acc;
                  } else {
                    return Belt_Array.concatMany([
                                [s1],
                                acc
                              ]);
                  }
                } else {
                  return Belt_Array.concatMany([
                              [s1],
                              acc
                            ]);
                }
              }));
}

export {
  smallest ,
  inspect ,
  dedupe ,
}
/* No side effect */
