// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function smallest(arr, size) {
  return Core__Option.map(arr[0], (function (head) {
                return Core__Array.reduce(arr, head, (function (small, value) {
                              if (size(small) < size(value)) {
                                return small;
                              } else {
                                return value;
                              }
                            }));
              }));
}

function inspect(x) {
  console.log(x);
  return x;
}

function dedupe(arr, eq) {
  var x = arr[0];
  if (x === undefined) {
    return [];
  }
  var x$1 = Caml_option.valFromOption(x);
  return Belt_Array.concatMany([
              [x$1],
              dedupe(arr.slice(1).filter(function (y) {
                        return !eq(x$1, y);
                      }), eq)
            ]);
}

export {
  smallest ,
  inspect ,
  dedupe ,
}
/* No side effect */
