// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Polar from "./Polar.res.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.js";

var centerSphere = {
  color: [
    255,
    0,
    0
  ],
  center: {
    x: 0.0,
    y: 0.0,
    z: 0.0
  },
  radius: 2.0
};

var colors = Core__Array.toShuffled([
      [
        255,
        0,
        0
      ],
      [
        0,
        255,
        0
      ],
      [
        0,
        0,
        255
      ],
      [
        255,
        255,
        0
      ],
      [
        0,
        255,
        255
      ],
      [
        255,
        0,
        255
      ],
      [
        100,
        0,
        0
      ],
      [
        0,
        100,
        0
      ],
      [
        0,
        0,
        100
      ],
      [
        100,
        100,
        0
      ],
      [
        0,
        100,
        100
      ],
      [
        100,
        0,
        100
      ]
    ]);

var spheres = (function (spheres) {
      return Belt_Array.concatMany([
                  [centerSphere],
                  spheres
                ]);
    })(Belt_Array.zip(colors, Polar.neighbors(centerSphere)).map(function (param) {
          var match = param[1];
          return {
                  color: param[0],
                  center: match.center,
                  radius: match.radius
                };
        }));

var planes = [];

var scene_triangles = [];

var scene = {
  spheres: spheres,
  triangles: scene_triangles,
  planes: planes
};

var eye = {
  x: 0.0,
  y: 25.0,
  z: 0.0
};

var red = [
  255,
  0,
  0
];

var green = [
  0,
  255,
  0
];

var blue = [
  0,
  0,
  255
];

var yellow = [
  255,
  255,
  0
];

var cyan = [
  0,
  255,
  255
];

var fuchsia = [
  255,
  0,
  255
];

var win = {
  normal: {
    origin: {
      x: 0.0,
      y: 15.0,
      z: 0.0
    },
    vector: {
      dx: 0.0,
      dy: -1.0,
      dz: 0.0
    }
  },
  up: {
    dx: 1.0,
    dy: 0.0,
    dz: 0.0
  },
  width: 8.0,
  height: 5.0,
  pxWidth: 400,
  pxHeight: 250
};

var white = [
  255,
  255,
  255
];

var enamel = [
  238,
  238,
  238
];

var dark = [
  68,
  68,
  68
];

export {
  eye ,
  centerSphere ,
  red ,
  green ,
  blue ,
  yellow ,
  cyan ,
  fuchsia ,
  colors ,
  spheres ,
  planes ,
  scene ,
  win ,
  white ,
  enamel ,
  dark ,
}
/* colors Not a pure module */
